 pipeline{
    agent any
    stages {
       

       stage('GetCode') {
            steps{
                git 'https://github.com/bio170/DevOps.git'
            }
         }        
       stage('Build') {
            steps {
                sh 'mvn clean package'
            }
         }
        stage('SonarQube analysis') {
        steps {
        withCredentials([string(credentialsId: 'Sonarqube-1test', variable: 'sonarqube')]) {
        sh "mvn sonar:sonar"
    
          } 

        }
        }

       
    }
}

